osx_image: xcode8.2
language: objective-c
script:
  - set -o pipefail && xcodebuild test -workspace Wolf.xcworkspace -scheme Wolf ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' -configuration Release
  - travis_wait 30 bundle exec pod lib lint
  
